### ISSUE TITLE
Is there have any TEST build?

### ISSUE THREAD

**Issue by odil24** [DonRomanooo/GenepiRender#24]
? interested on it

**Comment by romainaugier** [comment]
Not yet, I'm working on it !

**Comment by odil24** [comment]
> 
> 
> Not yet, I'm working on it !

can you post any latest render?

**Comment by romainaugier** [comment]
> can you post any latest render?

Latest renders are in the presentation page. I've refactored a lot of code and most of it is the ui, so no new rendering or shading features for now (but coming soon).

**Comment by odil24** [comment]
Looking forward to this))
